import type { Doctor, Localized, Specialty } from "./types";
export const localized = (ar: string, en: string, he: string): Localized => ({
  ar,
  en,
  he,
});
export const specialties: Record<Specialty, Localized> = {
  family: localized("طب العائلة", "Family medicine", "רפואת משפחה"),
  cardiology: localized("أمراض القلب", "Cardiology", "קרדיולוגיה"),
  dermatology: localized("الأمراض الجلدية", "Dermatology", "רפואת עור"),
  orthopedics: localized("جراحة العظام", "Orthopedics", "אורתופדיה"),
  neurology: localized("طب الأعصاب", "Neurology", "נוירולוגיה"),
  pediatrics: localized("طب الأطفال", "Pediatrics", "רפואת ילדים"),
  gynecology: localized("صحة المرأة", "Gynecology", "רפואת נשים"),
  psychiatry: localized("الطب النفسي", "Psychiatry", "פסיכיאטריה"),
  ent: localized("أنف وأذن وحنجرة", "Ear, nose & throat", "אף אוזן גרון"),
  physiotherapy: localized("العلاج الطبيعي", "Physiotherapy", "פיזיותרפיה"),
};
export const specialtyDescriptions: Record<Specialty, Localized> = {
  family: localized(
    "رعاية عامة ومتابعة دورية، مع طبيب يعرف الصورة الكاملة.",
    "General care and ongoing follow-ups, with a doctor who sees the whole picture.",
    "טיפול כללי ומעקב שוטף, עם רופא שרואה את התמונה המלאה.",
  ),
  cardiology: localized(
    "استشارات متخصصة ومتابعة صحة القلب والدورة الدموية.",
    "Specialist consultations for heart and cardiovascular care.",
    "ייעוץ מומחים לבריאות הלב וכלי הדם.",
  ),
  dermatology: localized(
    "استشارات ومتابعة العناية بالبشرة والشعر والأظافر.",
    "Consultations and follow-up care for skin, hair and nails.",
    "ייעוץ ומעקב לבריאות העור, השיער והציפורניים.",
  ),
  orthopedics: localized(
    "رعاية العظام والمفاصل والحركة، من الاستشارة إلى المتابعة.",
    "Bone, joint and movement care, from consultation to follow-up.",
    "טיפול בעצמות, מפרקים ותנועה, מייעוץ ועד מעקב.",
  ),
  neurology: localized(
    "استشارات في طب الأعصاب ومتابعة الحالات مع مختص.",
    "Neurology appointments and follow-ups with a specialist.",
    "ייעוץ ומעקב עם מומחה בנוירולוגיה.",
  ),
  pediatrics: localized(
    "رعاية الأطفال ومتابعة النمو في مختلف المراحل العمرية.",
    "Care for children and developmental follow-ups at every stage.",
    "טיפול בילדים ומעקב התפתחות בכל שלב.",
  ),
  gynecology: localized(
    "استشارات لصحة المرأة ورعاية تراعي احتياجاتها.",
    "Consultations and care centered on women’s health.",
    "ייעוץ וטיפול המתמקדים בבריאות האישה.",
  ),
  psychiatry: localized(
    "مساحة مهنية للاستشارة والمتابعة في الصحة النفسية.",
    "Professional consultations and follow-ups for mental health.",
    "ייעוץ מקצועי ומעקב בבריאות הנפש.",
  ),
  ent: localized(
    "استشارات متخصصة في صحة الأذن والأنف والحنجرة.",
    "Specialist care for ear, nose and throat concerns.",
    "טיפול מומחים בבריאות האוזן, האף והגרון.",
  ),
  physiotherapy: localized(
    "جلسات تقييم ومتابعة للحركة والتأهيل الوظيفي.",
    "Movement assessments and physical rehabilitation appointments.",
    "הערכת תנועה ופגישות שיקום גופני.",
  ),
};
export const languageNames = { ar: "العربية", en: "English", he: "עברית" };
export const cities = {
  haifa: localized("حيفا", "Haifa", "חיפה"),
  nazareth: localized("الناصرة", "Nazareth", "נצרת"),
  jaffa: localized("تل أبيب–يافا", "Tel Aviv–Jaffa", "תל אביב–יפו"),
};
export const doctors: Doctor[] = [
  {
    id: "lina-mansour",
    name: localized("د. لينا منصور", "Dr. Lina Mansour", "ד״ר לינא מנסור"),
    initials: "LM",
    specialty: "family",
    city: cities.haifa,
    cityId: "haifa",
    languages: ["ar", "he", "en"],
    experience: 12,
    consultations: ["clinic", "video"],
    nextDay: 1,
    color: "mint",
  },
  {
    id: "sami-khalil",
    name: localized("د. سامي خليل", "Dr. Sami Khalil", "ד״ר סאמי ח׳ליל"),
    initials: "SK",
    specialty: "cardiology",
    city: cities.nazareth,
    cityId: "nazareth",
    languages: ["ar", "he"],
    experience: 18,
    consultations: ["clinic"],
    nextDay: 1,
    color: "blue",
  },
  {
    id: "nour-haddad",
    name: localized("د. نور حداد", "Dr. Nour Haddad", "ד״ר נור חדאד"),
    initials: "NH",
    specialty: "dermatology",
    city: cities.haifa,
    cityId: "haifa",
    languages: ["ar", "en", "he"],
    experience: 9,
    consultations: ["clinic", "video"],
    nextDay: 2,
    color: "sand",
  },
  {
    id: "adam-saleh",
    name: localized("د. آدم صالح", "Dr. Adam Saleh", "ד״ר אדם סאלח"),
    initials: "AS",
    specialty: "orthopedics",
    city: cities.jaffa,
    cityId: "jaffa",
    languages: ["ar", "he", "en"],
    experience: 15,
    consultations: ["clinic"],
    nextDay: 3,
    color: "lavender",
  },
  {
    id: "maya-levi",
    name: localized("د. مايا ليفي", "Dr. Maya Levi", "ד״ר מאיה לוי"),
    initials: "ML",
    specialty: "family",
    city: cities.jaffa,
    cityId: "jaffa",
    languages: ["he", "en"],
    experience: 11,
    consultations: ["clinic", "video"],
    nextDay: 2,
    color: "blue",
  },
  {
    id: "rami-nasser",
    name: localized("د. رامي ناصر", "Dr. Rami Nasser", "ד״ר ראמי נאסר"),
    initials: "RN",
    specialty: "dermatology",
    city: cities.nazareth,
    cityId: "nazareth",
    languages: ["ar", "he"],
    experience: 14,
    consultations: ["clinic", "video"],
    nextDay: 4,
    color: "mint",
  },
  {
    id: "yara-abbas",
    name: localized("د. يارا عباس", "Dr. Yara Abbas", "ד״ר יארא עבאס"),
    initials: "YA",
    specialty: "neurology",
    city: cities.haifa,
    cityId: "haifa",
    languages: ["ar", "he", "en"],
    experience: 13,
    consultations: ["clinic", "video"],
    nextDay: 2,
    color: "sand",
  },
  {
    id: "omar-daher",
    name: localized("د. عمر ظاهر", "Dr. Omar Daher", "ד״ר עומר דאהר"),
    initials: "OD",
    specialty: "pediatrics",
    city: cities.nazareth,
    cityId: "nazareth",
    languages: ["ar", "he"],
    experience: 16,
    consultations: ["clinic", "video"],
    nextDay: 1,
    color: "blue",
  },
  {
    id: "dana-khoury",
    name: localized("د. دانا خوري", "Dr. Dana Khoury", "ד״ר דנא ח׳ורי"),
    initials: "DK",
    specialty: "gynecology",
    city: cities.haifa,
    cityId: "haifa",
    languages: ["ar", "he", "en"],
    experience: 10,
    consultations: ["clinic"],
    nextDay: 3,
    color: "lavender",
  },
  {
    id: "tarek-awad",
    name: localized("د. طارق عوض", "Dr. Tarek Awad", "ד״ר טארק עוואד"),
    initials: "TA",
    specialty: "psychiatry",
    city: cities.jaffa,
    cityId: "jaffa",
    languages: ["ar", "he"],
    experience: 14,
    consultations: ["clinic", "video"],
    nextDay: 2,
    color: "mint",
  },
];
export function appointmentDays(offset = 1) {
  return Array.from({ length: 5 }, (_, i) => {
    const d = new Date();
    d.setDate(d.getDate() + offset + i);
    return `${d.getFullYear()}-${String(d.getMonth() + 1).padStart(2, "0")}-${String(d.getDate()).padStart(2, "0")}`;
  });
}
export const appointmentTimes = ["09:00", "10:30", "12:00", "14:30", "16:00"];
