"use client";
import {useState,useEffect,useCallback} from 'react';
import Link from 'next/link';
import {AuthGuard,ErrorNotice} from './auth';
import {PageHeading} from './ui';
import {useClinic} from './provider';
import {AppointmentList} from './dashboard';
import {adminApi} from '@/lib/api/admin';
import type {SpecialtyRecord,ServiceRecord} from '@/lib/api/services';
interface AdminDoctor {id:string;full_name:string;profile_id:string|null;specialty_id:string;bio:string;experience_years:number;languages:string[];consultation_fee:number;status:string;doctor_locations:{clinic_name:string;address:string;city:string}[];doctor_services:{service_id:string}[];}
interface Knowledge {id:string;title:string;status:string;active:boolean;language:string;document_type:string;}
export type Section='doctors'|'services'|'specialties'|'knowledge'|'appointments';
export function AdminPage({section}:{section:Section}){return <AuthGuard roles={['admin','super_admin']}><AdminWorkspace section={section}/></AuthGuard>;}
function AdminWorkspace({section}:{section:Section}){
 const {t,locale,reload}=useClinic();const [doctors,setDoctors]=useState<AdminDoctor[]>([]),[specialties,setSpecialties]=useState<SpecialtyRecord[]>([]),[services,setServices]=useState<ServiceRecord[]>([]),[documents,setDocuments]=useState<Knowledge[]>([]),[accounts,setAccounts]=useState<{id:string;full_name:string;role:string}[]>([]);
 const [edit,setEdit]=useState(''),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[version,setVersion]=useState(0);
 const load=useCallback(async()=>{try{const [d,sp,sv,k,a]=await Promise.all([adminApi.list<AdminDoctor>('doctors'),adminApi.list<SpecialtyRecord>('specialties'),adminApi.list<ServiceRecord>('services'),adminApi.list<Knowledge>('knowledge'),adminApi.list<{id:string;full_name:string;role:string}>('doctor-accounts')]);setDoctors(d);setSpecialties(sp);setServices(sv);setDocuments(k);setAccounts(a);}catch(e){setError((e as Error).message);}},[]);
 useEffect(()=>{void Promise.resolve().then(load);},[load]);
 async function run(action:()=>Promise<unknown>){setBusy(true);setError('');setNotice('');try{await action();setNotice(t('تم الحفظ','Saved','נשמר'));setEdit('');setVersion(v=>v+1);await load();await reload();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const titles:Record<Section,string>={doctors:t('الأطباء','Doctors','רופאים'),services:t('الخدمات','Services','שירותים'),specialties:t('التخصصات','Specialties','התמחויות'),knowledge:t('قاعدة المعرفة','Knowledge base','מאגר ידע'),appointments:t('المواعيد','Appointments','תורים')};
 const doctor=doctors.find(d=>d.id===edit);const catalog=(section==='services'?services:specialties).find(s=>s.id===edit);const location=doctor?.doctor_locations[0];
 return <div className="container page"><PageHeading eyebrow={t('إدارة المنصة','PLATFORM ADMINISTRATION','ניהול הפלטפורמה')} title={titles[section]}/><nav className="tabs">{Object.entries(titles).map(([key,label])=><Link className={key===section?'active':''} href={`/admin/${key}`} key={key}>{label}</Link>)}</nav><ErrorNotice error={error}/>{notice&&<p role="status">{notice}</p>}
 {section==='appointments'?<AppointmentList role="admin"/>:<div className="admin-layout"><section>
 {section==='doctors'&&doctors.map(d=><article className="live-row" key={d.id}><div><h3>{d.full_name}</h3><p>{d.status}</p></div><div className="row-actions"><button className="button outline small" onClick={()=>{setEdit(d.id);setVersion(v=>v+1);}}>{t('تعديل','Edit','עריכה')}</button>{d.status!=='approved'&&<button className="button small" disabled={busy} onClick={()=>run(()=>adminApi.approve(d.id))}>{t('اعتماد','Approve','אישור')}</button>}<button className="button outline small" disabled={busy||d.status==='inactive'} onClick={()=>run(()=>adminApi.remove('doctors',d.id))}>{t('إيقاف','Deactivate','השבתה')}</button></div></article>)}
 {(section==='services'||section==='specialties')&&(section==='services'?services:specialties).map(s=><article className="live-row" key={s.id}><div><h3>{s[`name_${locale}`]||s.name_en}</h3><p>{s.active?t('مفعّل','Active','פעיל'):t('متوقف','Inactive','לא פעיל')}</p></div><div className="row-actions"><button className="button outline small" onClick={()=>{setEdit(s.id);setVersion(v=>v+1);}}>{t('تعديل','Edit','עריכה')}</button><button className="button outline small" disabled={busy||!s.active} onClick={()=>run(()=>adminApi.remove(section,s.id))}>{t('إيقاف','Deactivate','השבתה')}</button></div></article>)}
 {section==='knowledge'&&documents.map(d=><article className="live-row" key={d.id}><div><h3>{d.title}</h3><p>{d.status} · {d.language} · {d.active?t('مفعّل','Active','פעיל'):t('متوقف','Inactive','לא פעיל')}</p><label className="file-replace">{t('استبدال الملف','Replace file','החלפת קובץ')}<input type="file" accept=".pdf,.docx,.txt" disabled={busy} onChange={e=>{const file=e.target.files?.[0];if(file){const data=new FormData();data.set('file',file);void run(()=>adminApi.upload(data,d.id));}}}/></label></div><div className="row-actions"><button className="button outline small" disabled={busy||d.status!=='completed'} onClick={()=>run(()=>adminApi.save('knowledge',{active:!d.active},d.id))}>{d.active?t('إيقاف','Deactivate','השבתה'):t('تفعيل','Activate','הפעלה')}</button><button className="button outline small" disabled={busy} onClick={()=>{if(window.confirm(t('حذف هذا المستند نهائيًا؟','Permanently delete this document?','למחוק את המסמך לצמיתות?')))void run(()=>adminApi.remove('knowledge',d.id));}}>{t('حذف','Delete','מחיקה')}</button></div></article>)}
 </section><aside><h2>{edit?t('تعديل السجل','Edit record','עריכת רשומה'):t('إضافة جديد','Add new','הוספה')}</h2>{edit&&<button className="text-link" onClick={()=>{setEdit('');setVersion(v=>v+1);}}>{t('إلغاء التعديل','Cancel edit','ביטול עריכה')}</button>}
 {section==='doctors'&&<form key={version} className="live-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>adminApi.save('doctors',{full_name:f.get('full_name'),profile_id:f.get('profile_id')||null,specialty_id:f.get('specialty_id'),bio:f.get('bio'),languages:String(f.get('languages')).split(',').map(s=>s.trim()).filter(Boolean),experience_years:Number(f.get('experience_years')),consultation_fee:Number(f.get('consultation_fee')),service_ids:f.getAll('service_ids'),location:{clinic_name:f.get('clinic_name'),address:f.get('address'),city:f.get('city')}},edit||undefined));}}>
 <label>{t('اسم الطبيب','Doctor name','שם הרופא')}<input name="full_name" defaultValue={doctor?.full_name} required minLength={2}/></label><label>{t('حساب الطبيب — يسجل أولًا ثم اربطه هنا','Doctor account — register first, then link here','חשבון רופא — יש להירשם ואז לקשר כאן')}<select name="profile_id" defaultValue={doctor?.profile_id||''}><option value="">{t('بدون حساب مرتبط','No linked account','ללא חשבון מקושר')}</option>{accounts.map(a=><option key={a.id} value={a.id}>{a.full_name} · {a.role}</option>)}</select></label>
 <label>{t('التخصص','Specialty','התמחות')}<select name="specialty_id" defaultValue={doctor?.specialty_id} required>{specialties.filter(s=>s.active).map(s=><option value={s.id} key={s.id}>{s[`name_${locale}`]||s.name_en}</option>)}</select></label>
 <label>{t('نبذة','Biography','אודות')}<textarea name="bio" defaultValue={doctor?.bio} required minLength={10} maxLength={8000}/></label><label>{t('اللغات — مفصولة بفواصل','Languages — comma separated','שפות — מופרדות בפסיקים')}<input name="languages" placeholder="ar,en,he" defaultValue={doctor?.languages?.join(',')} required/></label>
 <label>{t('سنوات الخبرة','Experience years','שנות ניסיון')}<input name="experience_years" type="number" min={0} max={80} defaultValue={doctor?.experience_years||0} required/></label><label>{t('رسوم الاستشارة ILS','Consultation fee ILS','מחיר ייעוץ ILS')}<input name="consultation_fee" type="number" min={0} step="0.01" defaultValue={doctor?.consultation_fee||0} required/></label>
 <fieldset><legend>{t('الخدمات','Services','שירותים')}</legend>{services.filter(s=>s.active).map(s=><label className="check-option" key={s.id}><input name="service_ids" type="checkbox" value={s.id} defaultChecked={doctor?.doctor_services.some(x=>x.service_id===s.id)}/>{s[`name_${locale}`]||s.name_en} · {s.price} ILS</label>)}</fieldset>
 <label>{t('العيادة','Clinic','מרפאה')}<input name="clinic_name" defaultValue={location?.clinic_name} required/></label><label>{t('العنوان','Address','כתובת')}<input name="address" defaultValue={location?.address} required/></label><label>{t('المدينة','City','עיר')}<input name="city" defaultValue={location?.city} required/></label><button className="button" disabled={busy}>{t('حفظ الطبيب','Save doctor','שמירת רופא')}</button></form>}
 {(section==='services'||section==='specialties')&&<form key={version} className="live-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);void run(()=>adminApi.save(section,{name_en:f.get('name_en'),name_ar:f.get('name_ar'),name_he:f.get('name_he'),description:f.get('description'),active:f.get('active')==='on',...(section==='services'?{duration_minutes:Number(f.get('duration_minutes')),price:Number(f.get('price')),consultation_type:f.get('consultation_type')}:{})},edit||undefined));}}>
 {(['ar','en','he'] as const).map(l=><label key={l}>{t('الاسم','Name','שם')} ({l})<input name={`name_${l}`} defaultValue={catalog?.[`name_${l}`]||''} required={l==='en'}/></label>)}<label>{t('الوصف','Description','תיאור')}<textarea name="description" defaultValue={catalog?.description||''}/></label>
 {section==='services'&&<><label>{t('المدة بالدقائق','Duration in minutes','משך בדקות')}<input name="duration_minutes" type="number" min={5} max={240} defaultValue={(catalog as ServiceRecord)?.duration_minutes||30} required/></label><label>{t('السعر ILS','Price ILS','מחיר ILS')}<input name="price" type="number" min={0} step="0.01" defaultValue={(catalog as ServiceRecord)?.price||0} required/></label><label>{t('نوع الاستشارة','Consultation type','סוג ייעוץ')}<select name="consultation_type" defaultValue={(catalog as ServiceRecord)?.consultation_type||'clinic'}><option value="clinic">{t('في العيادة','In clinic','במרפאה')}</option><option value="video">{t('بالفيديو','Video','וידאו')}</option></select></label></>}
 <label className="check-option"><input type="checkbox" name="active" defaultChecked={catalog?.active??true}/>{t('مفعّل','Active','פעיל')}</label><button className="button" disabled={busy}>{t('حفظ','Save','שמירה')}</button></form>}
 {section==='knowledge'&&<form key={version} className="live-form" onSubmit={e=>{e.preventDefault();const f=new FormData(e.currentTarget);if(!f.get('doctor_id'))f.delete('doctor_id');if(!f.get('specialty_id'))f.delete('specialty_id');void run(()=>adminApi.upload(f));}}><p>{t('تُرسل نصوص المستندات إلى Gemini لإنشاء الفهرس. ارفع محتوى معتمدًا للنشر فقط.','Document text is sent to Gemini for indexing. Upload only content approved for patient-facing use.','טקסט המסמכים נשלח ל־Gemini לאינדוקס. העלו רק תוכן מאושר לשימוש מול מטופלים.')}</p><label>{t('العنوان','Title','כותרת')}<input name="title" required minLength={2}/></label><label>{t('الملف — حتى 8 ميجابايت','File — up to 8 MB','קובץ — עד 8 MB')}<input type="file" name="file" accept=".pdf,.docx,.txt" required/></label><label>{t('اللغة','Language','שפה')}<select name="language"><option value="ar">العربية</option><option value="en">English</option><option value="he">עברית</option></select></label><label>{t('نوع المستند','Document type','סוג מסמך')}<input name="document_type" defaultValue="general" required maxLength={80}/></label><label>{t('الطبيب — اختياري','Doctor — optional','רופא — רשות')}<select name="doctor_id"><option value="">—</option>{doctors.map(d=><option key={d.id} value={d.id}>{d.full_name}</option>)}</select></label><label>{t('التخصص — اختياري','Specialty — optional','התמחות — רשות')}<select name="specialty_id"><option value="">—</option>{specialties.map(s=><option key={s.id} value={s.id}>{s[`name_${locale}`]||s.name_en}</option>)}</select></label><button className="button" disabled={busy}>{busy?t('جارٍ الرفع والفهرسة…','Uploading and indexing…','מעלים ומאנדקסים…'):t('رفع وفهرسة','Upload and index','העלאה ואינדוקס')}</button></form>}
 </aside></div>}</div>;
}
