"use client";
import {useState,useEffect,useCallback} from 'react';
import {AuthGuard,ErrorNotice} from './auth';
import {PageHeading} from './ui';
import {useClinic} from './provider';
import {AppointmentList,FileManager} from './dashboard';
import {api,json} from '@/lib/api/client';
import type {Slot} from '@/lib/api/doctors';
interface OwnDoctor {id:string;full_name:string;bio:string;experience_years:number;consultation_fee:number;languages:string[];status:string;}
export function DoctorWorkspace(){return <AuthGuard roles={['doctor']}><Workspace/></AuthGuard>;}
function Workspace(){const {t}=useClinic();const [tab,setTab]=useState('appointments'),[doctor,setDoctor]=useState<OwnDoctor|null>(null),[slots,setSlots]=useState<Slot[]>([]),[error,setError]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const load=useCallback(async()=>{try{const [d,s]=await Promise.all([api<OwnDoctor>('/doctor/profile'),api<Slot[]>('/doctor/availability')]);setDoctor(d);setSlots(s);}catch(e){setError((e as Error).message);}},[]);useEffect(()=>{void Promise.resolve().then(load);},[load]);
 return <div className="container page"><PageHeading eyebrow={t('مساحة الطبيب','DOCTOR WORKSPACE','מרחב הרופא')} title={doctor?.full_name||t('إدارة الرعاية','Manage care','ניהול טיפול')}/><ErrorNotice error={error}/>{notice&&<p role="status">{notice}</p>}<div className="tabs">{[['appointments',t('المواعيد','Appointments','תורים')],['availability',t('الأوقات المتاحة','Availability','זמינות')],['profile',t('الملف المهني','Professional profile','פרופיל מקצועי')],['documents',t('المستندات','Documents','מסמכים')]].map(([id,label])=><button className={tab===id?'active':''} key={id} onClick={()=>setTab(id)}>{label}</button>)}</div>
 {tab==='appointments'&&<AppointmentList role="doctor"/>}
 {tab==='availability'&&<><form className="live-form" onSubmit={async e=>{e.preventDefault();const form=e.currentTarget;setBusy(true);setError('');try{const f=new FormData(form);await api('/doctor/availability',{method:'POST',body:json(Object.fromEntries(f))});form.reset();await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><p>{t('جميع الأوقات بتوقيت القدس','All times use Jerusalem timezone','כל הזמנים לפי שעון ירושלים')}</p><label>{t('التاريخ','Date','תאריך')}<input name="date" type="date" required/></label><label>{t('من','From','מ־')}<input name="start_time" type="time" required/></label><label>{t('إلى','Until','עד')}<input name="end_time" type="time" required/></label><button className="button" disabled={busy}>{t('إضافة وقت متاح','Add available time','הוספת מועד פנוי')}</button></form>{slots.map(s=><div className="live-row" key={s.id}><span>{s.date} · {s.start_time.slice(0,5)}–{s.end_time.slice(0,5)}</span><button className="button outline small" disabled={busy} onClick={async()=>{setBusy(true);try{await api(`/doctor/availability/${s.id}`,{method:'DELETE'});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{t('إزالة','Remove','הסרה')}</button></div>)}</>}
 {tab==='profile'&&doctor&&<form className="live-form" onSubmit={async e=>{e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await api('/doctor/profile',{method:'PATCH',body:json({bio:f.get('bio'),languages:String(f.get('languages')).split(',').map(s=>s.trim()).filter(Boolean),experience_years:Number(f.get('experience_years')),consultation_fee:Number(f.get('consultation_fee'))})});await load();setNotice(t('حُفظ الملف وأُرسل للمراجعة.','Profile saved and submitted for review.','הפרופיל נשמר ונשלח לבדיקה.'));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}><label>{t('نبذة','Biography','אודות')}<textarea name="bio" defaultValue={doctor.bio} required minLength={10} maxLength={8000}/></label><label>{t('اللغات — مفصولة بفواصل','Languages — comma separated','שפות — מופרדות בפסיקים')}<input name="languages" defaultValue={doctor.languages?.join(',')} required/></label><label>{t('سنوات الخبرة','Years of experience','שנות ניסיון')}<input name="experience_years" type="number" min={0} max={80} defaultValue={doctor.experience_years} required/></label><label>{t('رسوم الاستشارة ILS','Consultation fee ILS','מחיר ייעוץ ILS')}<input name="consultation_fee" type="number" min={0} step="0.01" defaultValue={doctor.consultation_fee} required/></label><button className="button" disabled={busy}>{t('حفظ للمراجعة','Save for review','שמירה לבדיקה')}</button></form>}
 {tab==='documents'&&<FileManager bucket="doctor-documents"/>}</div>;
}
